# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Syllabus
    url: 'https://www.graduateinstitute.ch/courses' # Insert the URL to your PDF syllabus here
    weight: 1
  - name: Classes
    url: 'post'
    weight: 2
  - name: Resources
    url: 'courses/resources/'
    weight: 3
  - name: '<i class="fab fa-slack"></i>'
    url: "https://slack.com"
    weight: 4
  # - name: Publications
  #   url: '#featured'
  #   weight: 50
  # - name: Courses
  #   url: courses/
  #   weight: 60
  # - name: Contact
  #   url: '#contact'
  #   weight: 70
